### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by drpaneas** [toshimaru/auto-author-assign#22]
I get an error 

```
Run toshimaru/auto-author-assign@v1.1.2
  with:
    repo-token: ***
Error: Resource not accessible by integration
```

my `yml` looks like this:

```
name: 'Auto Author Assign'
on:
  pull_request:
    types: [opened, reopened]
jobs:
  add-assignees:
    runs-on: ubuntu-latest
    steps:
      - name: auto-author-assign
        uses: toshimaru/auto-author-assign@v1.1.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

**Comment by drpaneas** [comment]
Can this be that `pull_request` is not enough anymore?
I am trying to check if `pull_request_target` works better https://github.com/drpaneas/romie/pull/59/files

**Comment by drpaneas** [comment]
Using `pull_request_target` works.

**Comment by toshimaru** [comment]
@drpaneas I'm not sure why it raises the error when you use `pull_request` event. 🤔 
 
On my repository, it works without error:
https://github.com/toshimaru/RailsTwitterClone/pull/877

My Configuration:

```yml
name: 'Auto Author Assign'
on:
  pull_request:
    types: [opened, reopened]
jobs:
  add-assignees:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v1.1.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

https://github.com/toshimaru/RailsTwitterClone/blob/05f2e64a05f92420c7e0287c5352e2cce3487c02/.github/workflows/auto-author-assign.yml#L1-L11
