### ISSUE TITLE
how check if PR already assigned to avoid run the job?

### ISSUE THREAD

**Issue by AugustoCalaca** [toshimaru/auto-author-assign#29]

**Comment by yasudanaoya** [comment]
@AugustoCalaca 
I am also in trouble.

Did you solve it?

**Comment by jonathanstiansen** [comment]
I'm 95% sure it's not possible, it would have to go in the `on` block to run any machine - and those are limited to workflow events, not other data

**Comment by beastawakens** [comment]
I'm trying something like:

```yaml
jobs:
  assign-author:
    if: ${{ !contains(github.event.pull_request.assignees, '') }}
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v2.1.1
```

**Comment by ClaudioConsolmagno** [comment]
This worked for me:
```
jobs:
  auto-assign-pr-to-author:
    if: ${{ github.event.pull_request.assignees == null || toJSON(github.event.pull_request.assignees) == '[]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.1.1
```
